version: '3.8'

services:
  # 1. Django/Gunicorn 서비스 (우리가 만든 이미지)
  backend:
    build: .
    container_name: reframe-backend-container
    env_file: .env
    command: python -m gunicorn --bind 0.0.0.0:8000 config.wsgi
    # Nginx가 파일을 찾을 수 있도록 media 폴더를 공유합니다.
    volumes:
      - ./media:/app/media 

  # 2. Nginx 서비스 (Nginx 공식 이미지)
  nginx:
    image: nginx:latest
    container_name: reframe-nginx-container
    ports:
      - "80:80" # 내 컴퓨터 80 포트를 Nginx 80 포트에 연결
    volumes:
      # Nginx가 우리 설정 파일을 사용할 수 있도록 연결
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      # Nginx가 media 파일을 직접 서빙할 수 있도록 backend와 폴더 공유
      - ./media:/app/media
    depends_on:
      - backend # Nginx가 backend보다 나중에 켜지도록 순서 지정