version: '3.8'

services:
  # 1. Django/Gunicorn 서비스 (우리가 만든 이미지)
  backend:
    build: .
    container_name: reframe-backend-container
    env_file: .env
    command: python -m gunicorn --bind 0.0.0.0:8000 config.wsgi
    # Nginx가 파일을 찾을 수 있도록 media 폴더를 공유합니다.
    volumes:
      - ./media:/app/media 
      - ./static_root:/app/static

  # 2. Nginx 서비스 (Nginx 공식 이미지)
  nginx:
    image: nginx:latest
    container_name: reframe-nginx-container
    ports:
      - "80:80"
      - "443:443"  # 443 포트
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./media:/app/media:ro
      - ./static_root:/app/static:ro
      # GCP 서버의 SSL 인증서 폴더를 컨테이너와 공유
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /etc/letsencrypt/options-ssl-nginx.conf:/etc/letsencrypt/options-ssl-nginx.conf:ro
      - /etc/letsencrypt/ssl-dhparams.pem:/etc/letsencrypt/ssl-dhparams.pem:ro
      # Certbot 갱신을 위한 임시 폴더 공유 (선택 사항이지만 추천)
      - /var/www/certbot:/var/www/certbot:ro
    depends_on:
      - backend