# Generated by Django 5.2.6 on 2025-10-30 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_adminfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='nickname',
            field=models.CharField(blank=True, default='익명', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='nickname',
            field=models.CharField(blank=True, default='익명', max_length=50, null=True),
        ),
    ]
